### ISSUE TITLE
config crash in version 'kaos'

### ISSUE THREAD

**Issue by punk-t** [zioth/dokuwiki-autotooltip#21]
Hello,

the plugin seems to crash the config page and the `~~INFO:syntaxplugins~~` tool.

Plugin itself seems to work.

To reproduce:

- have DW version 2024-02-06 "Kaos"
- install & enable plugin
- go to DW admin config page
- admire the error message ("ArgumentCountError: 4 arguments are required, 2 given")

**Comment by zioth** [comment]
This works fine for me, so it must be Kaos. I can probably take a look on Sunday. Shouldn't be hard to fix.

**Comment by zioth** [comment]
Looks like this is a bug with many plugins in Kaos. I've reported the issue here: https://github.com/dokuwiki/dokuwiki/issues/4204

In the mean time, I've added a work-around to all of my plugins.

If you see this again with plugins other than mine, you can fix it by editing "plugin.info.txt" for the offending plugin, and making sure the "email" line is present, and that every line has both a name and a value.

**Comment by punk-t** [comment]
Thank you very much.

I can confirm both, your fix as well as your hint.
