### ISSUE TITLE
Fetch output from description plugin

### ISSUE THREAD

**Issue by vaniwiki** [zioth/dokuwiki-autotooltip#5]
I was just wishing for such a plugin, and this comes very close, except that its automatic mode only works with the abstract created by DokuWiki. I have tens of thousands of pages, each of them with a unique description set by the description plugin. This description does not get stored in the metadata, but is only computed at runtime (I guess).

It would be nice to be able to show this custom description instead of the auto generated abstract. :)

**Comment by zioth** [comment]
The description plugin creates its own metadata, so this is actually really easy! The next update -- probably in a day or two -- will have this feature. It will also have a feature I really like, which is to add tooltips to every internal link on your wiki.

**Comment by zioth** [comment]
I had some unexpected free time. Both features are complete. Thanks for the suggestion!

**Comment by vaniwiki** [comment]
And thank you for implementing! I was thinking that the automatic tooltip for every link was maybe too much to ask for. :) This functionality was there in Bootstrap3 with the semantic plugin, but similarly not fetching from the description plugin.

However... I am using purplenumbers with its own renderer mode. So how to combine the two? :)

**Comment by zioth** [comment]
@ahaituki Unfortunately, DokuWiki only supports one renderer plugin at a time. I've submitted a feature request, but they've been discussing that feature for years, so it could be a while.

In the meantime, my autolink4 plugin might get you part of the way there. It can be configured to add a tooltip to every link it creates.

I also might be able to do this with a sytax plugin instead of a renderer plugin, by overriding the default handling of `[[...]]`. I'll create a new issue and copy you.

**Comment by zioth** [comment]
@ahaituki It's going to be a lot more difficult than I thought to do this with a syntax plugin, and it would be hard to maintain forward-compatibility if I did. Unfortunately, you'll have to choose between purplenumbers and autotooltip until Doku allows multiple renderers. :(
