### ISSUE TITLE
Can’t close tooltip on mobile / touchscreen

### ISSUE THREAD

**Issue by gudnimg** [zioth/dokuwiki-autotooltip#8]
Probably not an issue but is it possible to add an event or function to detect if the user clicks/touches somewhere else on the screen in order to close the tooltip?

Right now if you trigger the tooltip the only way to get rid of it is to refresh the page.

**Comment by zioth** [comment]
Sorry for the year-long delay! I just tried this on mobile (Android/Chrome), and the tooltip closes when I touch somewhere outside of it. Do you remember what browser/device you were using?

**Comment by gudnimg** [comment]
No problem, better late than never! :) 

Huh I just tried it again on my phone. I used Safari on iOS last year, and it seems to work now like you described. Guess I can now use this everywhere on my wiki :D

I tried Chrome as well on iOS, that works too!

**Comment by zioth** [comment]
Great! I like closing issues without having to do anything! :)

**Comment by zioth** [comment]
Of course, tooltips on mobile are an issue mobile apps have been dealing with since the beginning. There's really no intuitive way to show a tooltip, and since space is so limited, you're often left with a row of obscure icons with no explanation. My favorite example is in WhatsApp: There's a a curved-left arrow next to a curved-right arrow. One quotes, while the other shares. Completely different behavior for nearly identical icons, with no explanation.

One solution is to add question mark icons next to tooltip-aware context, and you tap the question mark to get a tooltip, instead of the context item itself. However, that doesn't work for a wiki. You don't want your page filled up with question marks.
